### ISSUE TITLE
ebu-run error with consumer node/filesystem carriage

### ISSUE THREAD

**Issue by SKHameed86** [ebu/ebu-tt-live-toolkit#409]
**UPDATE - 13/04/2017**
Done some investigating and it seems like this issue has been around for a while.

At first, the error seems to have been:
```
File "/Users/hamees01/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2647, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'ebu-run') not found
```
Then at: https://github.com/ebu/ebu-tt-live-toolkit/commit/fd8e2037f39de45ad2e90a96611068b637895660
```
File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/adapters/node_carriage.py", line 134, in __init__
    self._expects = consumer_carriage.provides()
AttributeError: 'NoneType' object has no attribute 'provides'
```

And finally, from: https://github.com/ebu/ebu-tt-live-toolkit/commit/73b702ed846ab24cdcd95fc71da2cb746e0408e3
```
File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/carriage.py", line 111, in __init__
    manifest_path=config.manifest_file,
  File "/Users/hamees01/env/lib/python2.7/site-packages/configman/dotdict.py", line 363, in __getattr__
    raise KeyError(key)
KeyError: 'manifest_file'
```

At least, that's what I'm understanding has been happening.
<===========================================>

**ORIGINAL ISSUE - 12/04/2017**
This is my custom consumer node:

```{
  "nodes": {
    "node1": {
      "id": "consumer1",
      "type": "simple-consumer",
      "input": {
        "carriage": {
          "type": "filesystem",
          "manifest_file": "export/manifest_TestSequence1.txt"
        }
      }
    }
  }
}
```
Upon running it with: `ebu-run --admin.conf=ebu_tt_live/examples/config/simple_consumer_fs.json`

The following is output:

```
Traceback (most recent call last):
  File "/Users/hamees01/env/bin/ebu-run", line 11, in <module>
    load_entry_point('ebu-tt-live', 'console_scripts', 'ebu-run')()
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/scripts/ebu_run.py", line 42, in main
    app = create_app()
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/__init__.py", line 33, in create_app
    new_app = AppConfig(**kwargs)
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/__init__.py", line 62, in __init__
    self._nodes = config.nodes.type.configure_component(config, config.nodes)
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/node.py", line 370, in configure_component
    instance._nodes.append(item.type.configure_component(config, item))
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/common.py", line 53, in configure_component
    return cls(config=config, local_config=local_config)
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/node.py", line 94, in __init__
    self._create_input(config)
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/node.py", line 60, in _create_input
    config, self.config.input.carriage
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/common.py", line 53, in configure_component
    return cls(config=config, local_config=local_config)
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/carriage.py", line 111, in __init__
    manifest_path=config.manifest_file,
  File "/Users/hamees01/env/lib/python2.7/site-packages/configman/dotdict.py", line 363, in __getattr__
    raise KeyError(key)
KeyError: 'manifest_file'
```

**Comment by nigelmegitt** [comment]
Hmm, I think this works with WebSocket and Direct carriage mechanisms, and Direct also needs a key to identify the "pipe" so I'm expecting the code to be very similar. The next thing I would do is a line by line review of the code to see what differences exist between working code and non-working code. Alternatively (and more usefully, probably) do this dynamically using a debugger.

**Comment by EyalLavi** [comment]
@SKHameed86 as the original reporter, could you please confirm this is fixed now?

**Comment by SKHameed86** [comment]
I can confirm that this issue is fixed - thanks @tomrosier !
