### ISSUE TITLE
ebu-run resequencer error with filesystem carriage

### ISSUE THREAD

**Issue by SKHameed86** [ebu/ebu-tt-live-toolkit#411]
This is my customer resequencer code:

```
{
  "nodes": {
    "node1": {
      "id": "resequencer1",
      "type": "resequencer",
      "sequence_identifier": "ReSequenced1",
      "segment_length": "5.0",
      "input": {
        "carriage": {
          "type": "filesystem",
          "manifest_file": "export/manifest_TestSequence1.txt"
        }
      }
    }
  }
}
```

When I run: `ebu-run --admin.conf=ebu_tt_live/examples/config/resequencer_fs.json`

This is the output:

```
`Traceback (most recent call last):
  File "/Users/hamees01/env/bin/ebu-run", line 11, in <module>
    load_entry_point('ebu-tt-live', 'console_scripts', 'ebu-run')()
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/scripts/ebu_run.py", line 42, in main
    app = create_app()
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/__init__.py", line 33, in create_app
    new_app = AppConfig(**kwargs)
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/__init__.py", line 62, in __init__
    self._nodes = config.nodes.type.configure_component(config, config.nodes)
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/node.py", line 370, in configure_component
    instance._nodes.append(item.type.configure_component(config, item))
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/common.py", line 53, in configure_component
    return cls(config=config, local_config=local_config)
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/node.py", line 142, in __init__
    self._create_input(config)
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/node.py", line 60, in _create_input
    config, self.config.input.carriage
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/common.py", line 53, in configure_component
    return cls(config=config, local_config=local_config)
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/carriage.py", line 111, in __init__
    manifest_path=config.manifest_file,
  File "/Users/hamees01/env/lib/python2.7/site-packages/configman/dotdict.py", line 363, in __getattr__
    raise KeyError(key)
KeyError: 'manifest_file'
```

**Comment by SKHameed86** [comment]
It was my mistake.
