### ISSUE TITLE
Resequencer auto and clock type issue

### ISSUE THREAD

**Issue by SKHameed86** [ebu/ebu-tt-live-toolkit#412]
```
(env) hamees01➜BBCDev/MediaPlatforms/ebu-tt-live-toolkit(release/3.0✗)» ebu-run --admin.conf=ebu_tt_live/examples/config/resequencer_fs.json
Traceback (most recent call last):
  File "/Users/hamees01/env/bin/ebu-run", line 11, in <module>
    load_entry_point('ebu-tt-live', 'console_scripts', 'ebu-run')()
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/scripts/ebu_run.py", line 42, in main
    app = create_app()
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/__init__.py", line 33, in create_app
    new_app = AppConfig(**kwargs)
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/__init__.py", line 57, in __init__
    **cm_args
  File "/Users/hamees01/env/lib/python2.7/site-packages/configman/config_manager.py", line 266, in __init__
    known_keys = self._overlay_expand()
  File "/Users/hamees01/env/lib/python2.7/site-packages/configman/config_manager.py", line 731, in _overlay_expand
    an_option.set_value(an_option.default)
  File "/Users/hamees01/env/lib/python2.7/site-packages/configman/option.py", line 124, in set_value
    new_value = self.from_string_converter(val)
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/clocks.py", line 42, in get_clock
    type_name=clock_type
ebu_tt_live.errors.ConfigurationError: No such component: clock


(env) hamees01➜BBCDev/MediaPlatforms/ebu-tt-live-toolkit(release/3.0✗)» ebu-run --admin.conf=ebu_tt_live/examples/config/resequencer_fs.json
Traceback (most recent call last):
  File "/Users/hamees01/env/bin/ebu-run", line 11, in <module>
    load_entry_point('ebu-tt-live', 'console_scripts', 'ebu-run')()
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/scripts/ebu_run.py", line 42, in main
    app = create_app()
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/__init__.py", line 33, in create_app
    new_app = AppConfig(**kwargs)
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/__init__.py", line 62, in __init__
    self._nodes = config.nodes.type.configure_component(config, config.nodes)
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/node.py", line 370, in configure_component
    instance._nodes.append(item.type.configure_component(config, item))
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/common.py", line 53, in configure_component
    return cls(config=config, local_config=local_config)
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/node.py", line 141, in __init__
    self._create_component(config)
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/config/node.py", line 133, in _create_component
    sequence_identifier=self.config.sequence_identifier
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/utils.py", line 358, in __call__
    instance = super(AutoRegisteringABCMeta, cls).__call__(*args, **kwargs)
  File "/Users/hamees01/BBCDev/MediaPlatforms/ebu-tt-live-toolkit/ebu_tt_live/node/consumer.py", line 86, in __init__
    self._last_segment_end = reference_clock.get_time()
AttributeError: 'NoneType' object has no attribute 'get_time'
```

**Comment by EyalLavi** [comment]
@SKHameed86 could you please add some descriptive text to explain the issue?

**Comment by SKHameed86** [comment]
According to the documentation, `clock type` can be `local`, `auto` or `clock`

As this issue was found when writing a `resequencer` config file, the node only works when the `clock type` is `local`.

I don't think this has been addressed yet.

**Comment by spoeschel** [comment]
I'm affected by a similar issue. I think this is just a typo in the docs for the allowed clock types. So only the values `local`, `auto` and `utc` are be allowed - while currently the "simple-producer" and "resequencer" nodes refer to `clock` instead of `utc`.
