### ISSUE TITLE
Decide on which python versions we support

### ISSUE THREAD

**Issue by frans-ebu** [ebu/ebu-tt-live-toolkit#46]
- [ ] check existing code/libraries
- [ ] decide
- [ ] add to CONTRIBUTING.md
- [ ] add to .travis.yml

**Comment by gilbrechbuhler** [comment]
Okay so tested with python 3 here is the error I get :
```
Traceback (most recent call last):
  File "/home/gil/.pyenv/versions/python3_test/bin/ebu-dummy-encoder", line 9, in <module>
    load_entry_point('ebu-tt-live', 'console_scripts', 'ebu-dummy-encoder')()
  File "/home/gil/.pyenv/versions/python3_test/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/gil/.pyenv/versions/python3_test/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/home/gil/.pyenv/versions/python3_test/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/home/gil/.pyenv/versions/python3_test/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/gil/work/python3_test/ebu-tt-live-toolkit/ebu_tt_live/scripts/ebu_dummy_encoder.py", line 3, in <module>
    from ebu_tt_live import bindings
  File "/home/gil/work/python3_test/ebu-tt-live-toolkit/ebu_tt_live/bindings/__init__.py", line 2, in <module>
    from .raw import *
  File "/home/gil/work/python3_test/ebu-tt-live-toolkit/ebu_tt_live/bindings/raw/__init__.py", line 28, in <module>
    import _ebuttm as _ImportedBinding__ebuttm
ImportError: No module named '_ebuttm'
```
What actually happens here is that pyxb generates the binding as if they reside in the PYTHONPATH, which is obviously not the case. Thos works in python2 because as it does not find the imports in PYTHONPATH it simply does relative import, our usage is based on that. However, python3 corrects this as it is not feature, and asks for relative imports to start with a .
```
import ._ebuttm
```
Even if pyxb does allow us to precise --module-prefix, doing --module-prefix=. generates:
```
import .._ebuttm
```
which is invalid syntax. I'm trying to find an easy solution here, maybe @kozmaz87 did test under python3 and found a solution but in the current state the code will not run with python3.

**Comment by nigelmegitt** [comment]
Pretty sure I've seen a solution by @kozmaz87 to this problem, but I can't remember what it was :-(

**Comment by gilbrechbuhler** [comment]
Sad, because I tried a lot of things, and I don't have many more ideas of how to solve this problem. I'm pretty sure everything else works.

**Comment by frans-ebu** [comment]
Well, I guess worst-case we could rewrite .._ebuttm into ._ebuttm in the binding files? But that is far from elegant...

**Comment by gilbrechbuhler** [comment]
Well actually the error comes from the file generated by pyxbgen command, this command is supposed to be run on the user's machine. I only see two methods, either :
- we generate them once, correct them and commit them, only regenerating them when the xsd changes
- or we add a scripts that goes through the file and corrects them automatically

The first solution would normally be considered ugly, but as the amount of xsd file is unlikely to grow and they are unlikely to change much, it would be applicable. The second solution is quite hard to apply.

But I'd wait on an input from @kozmaz87 as he knows pyxb better than me and may have an easier solution.

**Comment by kozmaz87** [comment]
ok 2.7 for now
