### ISSUE TITLE
'invalid syntax' error from nltk

### ISSUE THREAD

**Issue by johnjcamilleri** [ebu/ebu-tt-live-toolkit#533]
I was getting the following error when running `ebu-dummy-encoder`:
```
Traceback (most recent call last):
  File "/opt/env/bin/ebu-dummy-encoder", line 11, in <module>
    load_entry_point('ebu-tt-live', 'console_scripts', 'ebu-dummy-encoder')()
  File "/opt/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/opt/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/opt/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/ebu_tt_live/scripts/ebu_dummy_encoder.py", line 6, in <module>
    from ebu_tt_live.documents.ebutt3 import EBUTT3Document
  File "/opt/ebu_tt_live/documents/__init__.py", line 1, in <module>
    from .base import SubtitleDocument, TimeBase, DocumentSequence
  File "/opt/ebu_tt_live/documents/base.py", line 2, in <module>
    from ebu_tt_live.utils import ComparableMixin
  File "/opt/ebu_tt_live/utils.py", line 9, in <module>
    from nltk import BlanklineTokenizer, PunktSentenceTokenizer, WhitespaceTokenizer
  File "/opt/env/lib/python2.7/site-packages/nltk/__init__.py", line 128, in <module>
    from nltk.collocations import *
  File "/opt/env/lib/python2.7/site-packages/nltk/collocations.py", line 35, in <module>
    from nltk.probability import FreqDist
  File "/opt/env/lib/python2.7/site-packages/nltk/probability.py", line 333
    print("%*s" % (width, samples[i]), end=" ")
                                          ^

SyntaxError: invalid syntax
```

Turns out my version of nltk (3.5) doesn't work with Python 2.7. So in `setup.py` I had to add an upperbound:
```
    install_requires=[
        ...
        "nltk<3.5",
        ...
    ]
```

**Comment by nigelmegitt** [comment]
Thanks for the report @johnjcamilleri - I expect we will be moving to Python 3.7+ in the next release, so this may not arise. Nevertheless, good to have it logged.
